### ISSUE TITLE
this.engine.close is not a function

### ISSUE THREAD

**Issue by lokielse** [wxsocketio/wxapp-socket-io#12]
```
WAService.js:1 thirdScriptError
this.engine.close is not a function;at onSocketMessage callback function
TypeError: this.engine.close is not a function
    at Manager.close.Manager.disconnect (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:394:38)
    at Manager.destroy (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:382:14)
    at Socket.destroy (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:1907:17)
    at Socket.close.Socket.disconnect (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:1892:14)
    at Socket.onpacket (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:1862:18)
    at Manager.<anonymous> (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:672:21)
    at Manager.Emitter.emit (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:615:26)
    at http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:272:18
    at Manager.decoder (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:1677:9)
    at Manager.ondata (http://1603736195.appservice.open.weixin.qq.com/vendor/socket.io/index.js:271:14)
```

**Comment by lokielse** [comment]
连接成功后，服务端把连接关闭，客户端就会报这个错误。
